[mcp_servers.dart]
command = "dart"
args = ["mcp-server"]

[mcp_servers.dotto-figma]
url = "https://mcp.figma.com/mcp"

[mcp_servers.dotto-notion]
url = "https://mcp.notion.com/mcp"

[plugins."context7@context7-marketplace"]
enabled = true

[plugins."firebase@firebase"]
enabled = true
