[settings]
minimum_release_age = "7d"

[settings.ruby]
compile = false

[env]
_.path = ["{{env.HOME}}/.pub-cache/bin"]

[tools]
flutter = "3.44.0"
gcloud = "572.0.0"
java = "21.0.2"
node = "24.16.0"
"npm:@openapitools/openapi-generator-cli" = "2.32.0"
ruby = "4.0.5"

[tasks.pre-commit]
run = "dart run scripts/pre_commit.dart"

[tasks.setup]
run = [
  "bundle install",
  "dart pub global activate melos 7.8.1",
  "melos bootstrap",
  "melos run fetch:dart_defines",
]

[tasks.build]
run = "melos run gen:build_runner --no-select"

[tasks.app]
run = [
  "melos run gen:build_runner --no-select",
  "cd apps/dotto && flutter run --flavor dev --dart-define-from-file=dart_defines/dev.json",
]

[tasks.widgetbook]
run = [
  "melos run gen:build_runner --no-select",
  "cd packages/dotto_design_system && flutter run",
]

[tasks.test-unit]
run = "melos run test:unit"

[tasks.analyze]
run = "dart analyze apps/dotto/ packages/dotto_design_system/ scripts/"

[tasks.format]
run = "dart fix --apply && dart format apps/dotto/lib/ apps/dotto/test/ packages/dotto_design_system/lib/ scripts/"

[tasks.generate-openapi]
run = "openapi-generator-cli generate -i ./openapi/openapi.yaml -g dart-dio -o ./packages/dotto_api"
