// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsc1j7yHtPUjdhOJsNaCKy3b_SKo7d25Q',
    appId: '1:107577467292:android:99fa38c96f4496aa06e859',
    messagingSenderId: '107577467292',
    projectId: 'swift2023groupc',
    databaseURL:
        'https://swift2023groupc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swift2023groupc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL8312t_Wnd1skH2u9TOVYZR3hQuDNc5A',
    appId: '1:107577467292:ios:b60af28764a55b0a06e859',
    messagingSenderId: '107577467292',
    projectId: 'swift2023groupc',
    databaseURL:
        'https://swift2023groupc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swift2023groupc.appspot.com',
    androidClientId:
        '107577467292-29qkb9uv90ftvfvlubgu32kkv6ho5prl.apps.googleusercontent.com',
    iosClientId:
        '107577467292-pu651ukbgkes48ussv1bp6p50s28lb7n.apps.googleusercontent.com',
    iosBundleId: 'jp.ac.fun.dotto.stg',
  );
}
