targets:
  $default:
    # Widgetbook のエントリポイントを lib/ の外に置くため、生成対象に加える
    sources:
      - $package$
      - lib/**
      - test/**
      - widgetbook/**
      - pubspec.yaml
    builders:
      freezed:
        options:
          make_collections_unmodifiable: true
