platform :ios do
  ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "30"

  def get_app_store_connect_api_key
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT_BASE64"],
      is_key_content_base64: true,
    )
  end

  desc "Match Development"
  lane :match_development do
    match(
      type: "development",
      force_for_new_devices: true,
      api_key: get_app_store_connect_api_key,
      app_identifier: [
        'jp.ac.fun.dotto',
        'jp.ac.fun.dotto.prd',
        'jp.ac.fun.dotto.stg',
        'jp.ac.fun.dotto.dev',
      ]
    )
  end

  desc "Match Ad Hoc"
  lane :match_adhoc do
    match(
      type: "adhoc",
      force_for_new_devices: true,
      api_key: get_app_store_connect_api_key,
      app_identifier: [
        'jp.ac.fun.dotto',
        'jp.ac.fun.dotto.prd',
        'jp.ac.fun.dotto.stg',
        'jp.ac.fun.dotto.dev',
      ]
    )
  end

  desc "Match App Store"
  lane :match_appstore do
    match(
      type: "appstore",
      force_for_new_devices: true,
      api_key: get_app_store_connect_api_key,
      app_identifier: [
        'jp.ac.fun.dotto',
        'jp.ac.fun.dotto.prd',
        'jp.ac.fun.dotto.stg',
        'jp.ac.fun.dotto.dev',
      ]
    )
  end

  desc "Fetch Development"
  lane :match_development_readonly do
    setup_ci if ENV['CI']
    match(
      type: "development",
      force_for_new_devices: true,
      readonly: true,
      app_identifier: [
        'jp.ac.fun.dotto',
        'jp.ac.fun.dotto.prd',
        'jp.ac.fun.dotto.stg',
        'jp.ac.fun.dotto.dev',
      ]
    )
  end

  desc "Fetch Ad Hoc"
  lane :match_adhoc_readonly do
    setup_ci if ENV['CI']
    match(
      type: "adhoc",
      force_for_new_devices: true,
      readonly: true,
      app_identifier: [
        'jp.ac.fun.dotto',
        'jp.ac.fun.dotto.prd',
        'jp.ac.fun.dotto.stg',
        'jp.ac.fun.dotto.dev',
      ]
    )
  end

  desc "Fetch App Store"
  lane :match_appstore_readonly do
    setup_ci if ENV['CI']
    match(
      type: "appstore",
      force_for_new_devices: true,
      readonly: true,
      app_identifier: [
        'jp.ac.fun.dotto',
        'jp.ac.fun.dotto.prd',
        'jp.ac.fun.dotto.stg',
        'jp.ac.fun.dotto.dev',
      ]
    )
  end

  desc "Register devices"
  lane :register_new_devices do
    register_devices(
      devices_file: "fastlane/ios/devices.txt",
      api_key: get_app_store_connect_api_key,
    )
    match_development
    match_adhoc
  end

  desc "Reset build number"
  lane :reset_build_number do
    increment_build_number({
      build_number: 1,
      xcodeproj: "apps/dotto/ios/Runner.xcodeproj",
    })
  end

  desc "Pre-build"
  lane :pre_build do
    sh('melos', 'bootstrap')
    sh('melos', 'run', 'gen:build_runner', '--no-select')
  end

  desc "Flutter release build"
  lane :flutter_release_build do
    sh(
      'melos',
      'exec',
      '--scope=dotto',
      '--',
      'flutter',
      'build',
      'ipa',
      '--release',
      '--dart-define-from-file=dart_defines/production.json',
    )
  end

  desc "Build OTA"
  lane :build_ota do
    match_adhoc_readonly
    pre_build
    flutter_release_build
    build_app(
      workspace: "apps/dotto/ios/Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      clean: true,
      output_directory: "build",
      output_name: "dotto.ipa",
      export_method: "ad-hoc",
      export_options: {
        provisioningProfiles: {
          "jp.ac.fun.dotto" => "match AdHoc jp.ac.fun.dotto",
        },
      },
    )
  end

  desc "Build Production"
  lane :build_production do
    match_appstore_readonly
    pre_build
    flutter_release_build
    build_app(
      workspace: "apps/dotto/ios/Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      clean: true,
      output_directory: "build",
      output_name: "dotto.ipa",
      export_method: "app-store",
      export_options: {
        clean: true,
        provisioningProfiles: {
          "jp.ac.fun.dotto" => "match AppStore jp.ac.fun.dotto",
        },
      },
    )
  end

  desc "Deploy OTA"
  lane :deploy_ota do
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_APP_ID_IOS"],
    )
    if latest_release.nil?
      reset_build_number
    else
      increment_build_number(
        build_number: latest_release[:buildVersion].to_i + 1,
        xcodeproj: "apps/dotto/ios/Runner.xcodeproj",
      )
    end
    build_ota
    release = firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS"],
      groups: ENV["FIREBASE_APP_DISTRIBUTION_GROUPS"],
    )
    slack(
      message: "Dotto OTA #{release[:displayVersion]} (#{release[:buildVersion]}) deployed!",
      payload: {
        "iOS" => "[iOS #{release[:displayVersion]} (#{release[:buildVersion]})](#{release[:testingUri]})",
      },
      default_payloads: [:git_branch, :git_author, :last_git_commit, :last_git_commit_hash],
      attachment_properties: {
        image_url: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=#{release[:testingUri]}",
      },
      slack_url: ENV["SLACK_URL"],
    )
    reset_build_number
  end

  desc "Deploy to TestFlight"
  lane :deploy_to_testflight do
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
    build_production
    upload_to_testflight(
      skip_submission: true,
      notify_external_testers: true,
      skip_waiting_for_build_processing: true,
      # distribute_external: true,
      # groups: ["Dotto Developer"],
      # changelog: "",
    )
    reset_build_number
  end
end
